# Generated by Django 2.1.5 on 2019-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.IntegerField(verbose_name='MRN')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
