# Generated by Django 2.1.5 on 2019-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='disc',
            field=models.CharField(default='None', max_length=200, verbose_name='Disc'),
        ),
    ]
